### ISSUE TITLE
README.md out of date; global scope import no longer supported

### ISSUE THREAD

**Issue by Trial-In-Error** [jackfranklin/gulp-load-plugins#102]
Hi!

I have a use case where I'd like to attach the loaded plugins to the global scope, and I spent some time digging around for the option / flag to turn it on because the first line in the README (`Loads in any gulp plugins and attaches them to the global scope, or an object of your choice.`) implies that it's possible. After finding issue #28, it looks like it's not supported - could you update the README to no longer mention global scope?

Thanks! =)

**Comment by jackfranklin** [comment]
Hey, I'll try to get to this when I can but not sure when that'll be - alternatively if you were to submit a PR with an updated README I'd love to merge it :)

**Comment by jackfranklin** [comment]
Thanks for spotting the out of date part though :)

**Comment by Trial-In-Error** [comment]
See PR #103 for a slight change in wording! Cheers!
