### ISSUE TITLE
complete task execution 5x slower 

### ISSUE THREAD

**Issue by mrt123** [jackfranklin/gulp-load-plugins#109]
Running multiple tasks takes 143ms on average when using native require vs 900ms when using gulp-load-plugins.

Plugins involved :
`angularModules = require("gulp-angular-modules"),
    concat = require('gulp-concat'),
    del = require('del'),
    eventStream = require('event-stream'),
    less = require('gulp-less'),
    cssLint = require('gulp-csslint'),
    merge = require('merge-stream'),
    runSequence = require('run-sequence'),
    sourceMaps = require('gulp-sourcemaps'),
    templateCache = require('gulp-angular-templatecache');`

I'm loading with following options:
`pattern: ['*', '!gulp'], // the glob(s) to search for`
`scope: ['devDependencies']`

I have no extra dependencies in my dev-deps

**Comment by jackfranklin** [comment]
Interesting; if anything I'd expect a better performance due to the lazy loading that's on by default.

We could really do with some benchmarking / profiling to see if we can hunt down what's slow and start to fix it - not something I've done before, though. Do you have any thoughts on this? Pinging @callumacrae ?

**Comment by jackfranklin** [comment]
Could you also try passing the option:

```
requireFn: require
```

And see if that makes a difference?

Equally if you could get this repo online so I can easily run & compare that'd be awesome.

**Comment by callumacrae** [comment]
That's not good. Wonder if this module will be able to help us debug this: https://github.com/jaguard/time-require

+1 to an example repo: would be useful.

**Comment by jackfranklin** [comment]
@mrt123 have you an example repo to work against? I'd love to dig into this.

**Comment by jackfranklin** [comment]
https://github.com/stormuk/storm-base-theme/blob/master/gulpfile.babel.js from @lgladdy is a decent size to profile :)

**Comment by mrt123** [comment]
@jackfranklin 
I've updated Node to : v4.4.5  (previously had 2.x), and re-tested:

This is my https://github.com/mrt123/checkers-ng-2/blob/master/other/tools/gulpfile.js 

Even though my tasks are spread across multiple files (with use of 'require-dir' module), I've managed to test with a single gulpfile, just with 'compile' task alone, and it's still slow.

I have a task 'compile' which I'm testing against:
* loading plugs manually ~ **420ms**
* without `requireFn: require`    **1.05  to 1.2 seconds**
* with   `requireFn: require` option **1.05 to 1.76 seconds**


To test, You can overwrite my gulpfile with this:
```
var gulp = require('gulp');

var gulpLoadPlugins = require('gulp-load-plugins');
var plugs = gulpLoadPlugins({
    pattern: ['*', '!gulp'], // the glob(s) to search for
    scope: ['devDependencies']
});

var Project = require('./gulp-tasks/Project');
var project = new Project();

var BUILD_PATH = project.BUILD_PATH;

gulp.task('compile', function (callback) {
    plugs.runSequence(
        'compile-clean',
        [
            'compile-app.js',
            'compile-app.css',
            'compile-assets',
            'compile-vendors',
            'compile-templates'
        ],
        callback
    );
});

gulp.task('compile-clean', function () {
    var deletePath = BUILD_PATH + '/**/*';
    return plugs.del([deletePath], {force: true});
});

gulp.task('compile-app.js', function () {

    var subModulesStream = gulp.src(project.JS_SUB_MODULES)
        .pipe(plugs.angularModules(
            "app-sub-modules.js",
            {
                name: "app-sub-modules",
                modules: ['ui.router']
            }));

    var jsStream = gulp.src(project.JS_FILES)
        .pipe(plugs.wrap('(function(){\n"use strict";\n<%= contents %>\n})();'))
        .pipe(plugs.sourcemaps.init());

    var devStream = gulp.src(project.DEV_FILES);

    var queue = plugs.streamqueue(
        { objectMode: true },
        jsStream,
        subModulesStream,
        devStream
    );

    return queue
        .pipe(plugs.concat('app.js'))
        .pipe(plugs.sourcemaps.write())
        .pipe(gulp.dest(BUILD_PATH));
});

gulp.task('compile-app.css', function () {

    return gulp.src(project.CSS_FILES)
        .pipe(plugs.sourcemaps.init())
        .pipe(plugs.less())
        .pipe(plugs.csslint({    // will report what plugs.less compile misses.
            "qualified-headings": false,
            "ids": false,
            "bulletproof-font-face": false,
            "box-sizing": false,
            "duplicate-properties": false,
            "box-moplugs.del": false   // I don't need warnings for padding vs width/height
        }))
        .pipe(plugs.csslint.reporter())
        .pipe(plugs.concat('app.css'))
        .pipe(plugs.sourcemaps.write())
        .pipe(gulp.dest(BUILD_PATH));
});

gulp.task('compile-templates', function () {
    return gulp.src(project.TEMPLATES)
        .pipe(plugs.angularTemplatecache({
            module: 'templates',
            standalone: true
        }))
        .pipe(gulp.dest(BUILD_PATH));
});

gulp.task('compile-assets', function () {
    return gulp.src(project.ASSETS)
        .pipe(gulp.dest(BUILD_PATH));
});

gulp.task('compile-vendors', function () {
    return gulp.src(project.VENDORS)
        .pipe(gulp.dest(BUILD_PATH + '/lib'));
});
```

**Comment by jackfranklin** [comment]
Thank you! I'm a n00b in this area but would love to dig in. Any thoughts you have, please share them :)

**Comment by jackfranklin** [comment]
@mrt123 can you upgrade to Node 6? Also, what version of npm are you on?

I'm on Node 6.1 and npm 3.8.6 and for me there's not much time difference.

First I ran `time gulp compile` with `gulp-load-plugins` used, and then I replaced `gulp-load-plugins` with:

```js
var plugs = {
    runSequence: require('run-sequence'),
    del: require('del'),
    angularModules: require('gulp-angular-modules'),
    angularTemplatecache: require('gulp-angular-templatecache'),
    wrap: require('gulp-wrap'),
    sourcemaps: require('gulp-sourcemaps'),
    less: require('gulp-less'),
    express: require('gulp-express'),
    debug: require('gulp-debug'),
    csslint: require('gulp-csslint'),
    concat: require('gulp-concat'),
    streamqueue: require('streamqueue'),
}
```

And ran again. Results:

## With GLP
gulp compile  1.12s user 0.12s system 103% cpu 1.204 total
gulp compile  1.18s user 0.18s system 97% cpu 1.401 total
gulp compile  1.19s user 0.13s system 103% cpu 1.275 total
gulp compile  1.10s user 0.13s system 106% cpu 1.149 total
gulp compile  1.09s user 0.12s system 104% cpu 1.159 total

Average:  **1.2376**

## Without GLP
gulp compile  0.98s user 0.11s system 105% cpu 1.028 total
gulp compile  1.09s user 0.16s system 95% cpu 1.313 total
gulp compile  1.14s user 0.17s system 92% cpu 1.404 total
gulp compile  1.05s user 0.15s system 94% cpu 1.276 total
gulp compile  1.11s user 0.16s system 96% cpu 1.318 total

Average: **1.2678**

This is obviously very different to your results so I'm not sure what's going on. Would appreciate if you could rerun on a later version of Node or npm.

**Comment by jackfranklin** [comment]
@callumacrae do you fancy running the above too and seeing what you get?

**Comment by mrt123** [comment]
Results from 2nd machine (my previous results were from Macbook Pro, this is another Macbook Pro).

OS:  OSX 10.10.5 (14F27)
gulp-load-plugins@1.2.4

#### Node v5.3.0  / NPM v3.10.3
With GLP  / gulp compile   : 957,  758 , 772 , 762
Without GLP   / gulp compile   :  350,  351, 352 , 348

#### Node v6.3.0
With GLP  / gulp compile   : 802,  897 , 1.03 , 884
Without GLP   / gulp compile   :  385,  361,  472 , 370

**Comment by jackfranklin** [comment]
This is very strange that you're seeing such a perf difference and I'm not...I'm not sure what could be causing this :/

**Comment by mrt123** [comment]
What's your OS? Could you try in another machine?

**Comment by jackfranklin** [comment]
I'm on a 2015 13" MacBook Pro on OSX 10.11.4. I'm using nvm to manage Node versions.

Can you share with me the exact steps & Gulpfile(s) you used to run the tests? Maybe I made a mistake...

**Comment by mrt123** [comment]
##### `cd other/toolsl`
##### `npm install`
##### Overwrite https://github.com/mrt123/checkers-ng-2/blob/master/other/tools/gulpfile.js with code I've posted few posts back:
````
var gulp = require('gulp');

var gulpLoadPlugins = require('gulp-load-plugins');
var plugs = gulpLoadPlugins({
    pattern: ['*', '!gulp'], // the glob(s) to search for
    scope: ['devDependencies']
});

var Project = require('./gulp-tasks/Project');
var project = new Project();

var BUILD_PATH = project.BUILD_PATH;

gulp.task('compile', function (callback) {
    plugs.runSequence(
        'compile-clean',
        [
            'compile-app.js',
            'compile-app.css',
            'compile-assets',
            'compile-vendors',
            'compile-templates'
        ],
        callback
    );
});

gulp.task('compile-clean', function () {
    var deletePath = BUILD_PATH + '/**/*';
    return plugs.del([deletePath], {force: true});
});

gulp.task('compile-app.js', function () {

    var subModulesStream = gulp.src(project.JS_SUB_MODULES)
        .pipe(plugs.angularModules(
            "app-sub-modules.js",
            {
                name: "app-sub-modules",
                modules: ['ui.router']
            }));

    var jsStream = gulp.src(project.JS_FILES)
        .pipe(plugs.wrap('(function(){\n"use strict";\n<%= contents %>\n})();'))
        .pipe(plugs.sourcemaps.init());

    var devStream = gulp.src(project.DEV_FILES);

    var queue = plugs.streamqueue(
        { objectMode: true },
        jsStream,
        subModulesStream,
        devStream
    );

    return queue
        .pipe(plugs.concat('app.js'))
        .pipe(plugs.sourcemaps.write())
        .pipe(gulp.dest(BUILD_PATH));
});

gulp.task('compile-app.css', function () {

    return gulp.src(project.CSS_FILES)
        .pipe(plugs.sourcemaps.init())
        .pipe(plugs.less())
        .pipe(plugs.csslint({    // will report what plugs.less compile misses.
            "qualified-headings": false,
            "ids": false,
            "bulletproof-font-face": false,
            "box-sizing": false,
            "duplicate-properties": false,
            "box-moplugs.del": false   // I don't need warnings for padding vs width/height
        }))
        .pipe(plugs.csslint.reporter())
        .pipe(plugs.concat('app.css'))
        .pipe(plugs.sourcemaps.write())
        .pipe(gulp.dest(BUILD_PATH));
});

gulp.task('compile-templates', function () {
    return gulp.src(project.TEMPLATES)
        .pipe(plugs.angularTemplatecache({
            module: 'templates',
            standalone: true
        }))
        .pipe(gulp.dest(BUILD_PATH));
});

gulp.task('compile-assets', function () {
    return gulp.src(project.ASSETS)
        .pipe(gulp.dest(BUILD_PATH));
});

gulp.task('compile-vendors', function () {
    return gulp.src(project.VENDORS)
        .pipe(gulp.dest(BUILD_PATH + '/lib'));
});
````
####  Run `gulp compile`, few times
#### Record results

#### Overwrite:
````
var gulpLoadPlugins = require('gulp-load-plugins');
var plugs = gulpLoadPlugins({
    pattern: ['*', '!gulp'], // the glob(s) to search for
    scope: ['devDependencies']
});
````
with:
````
var plugs = {
    runSequence: require('run-sequence'),
    del: require('del'),
    angularModules: require('gulp-angular-modules'),
    angularTemplatecache: require('gulp-angular-templatecache'),
    wrap: require('gulp-wrap'),
    sourcemaps: require('gulp-sourcemaps'),
    less: require('gulp-less'),
    express: require('gulp-express'),
    debug: require('gulp-debug'),
    csslint: require('gulp-csslint'),
    concat: require('gulp-concat'),
    streamqueue: require('streamqueue'),
}
````
#### Run `gulp compile`, few times
#### Record results

**Comment by Moofx** [comment]
Yep. I can confirm that its about 5x slower than using require for each plugin.

**Comment by jackfranklin** [comment]
@Moofx, cool, could you share how you did that?

I'm not actively working with Gulp and profiling this tool right now but I am open to any PRs or discussions on how to improve this.

**Comment by Moofx** [comment]
It is very simple code. Just running style rules checker. I think that problem may be caused by user enviroment. I am running on **Win7**. Didn`t tested it on ubuntu yet. But I had so far problem with jshint that was needed to install it localy. (If it was installed globaly, it ended with [error](https://github.com/spalger/gulp-jshint/issues/131) )

**gulpfile.js**: 
`var gulp = require('gulp');
var args = require('yargs').argv;

var $ = require('gulp-load-plugins')({lazy: true});

gulp.task('check', function () {
    return gulp
  .src([
        './src/**/*.js',
        './*.js',
    ])
  .pipe($.if(args.verbose, $.print()))
  .pipe($.jscs())
  .pipe($.jshint())
  .pipe($.jshint.reporter('jshint-stylish', { verbose: true }))
  .pipe($.jshint.reporter('fail'));

  });`

**Comment by jameelmoses** [comment]
Closing for now due to inactivity. Happy to re-open if there are still performance issues, although I have yet to experience any myself.
