### ISSUE TITLE
Version 1.2.3 breaks gulp 3.9.1 + sass completely: No output

### ISSUE THREAD

**Issue by ayalon** [jackfranklin/gulp-load-plugins#113]
I did a fresh install with npm install today. If I start gulp with a sass task, there is **no output at all**.

If I downgrade to 1.2.2, everything works as expected.

package.json
```
{
  "name": "gh_zurb",
  "version": "0.0.3",
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-copy": "^0.0.2",
    "gulp-livereload": "^3.8.1",
    "gulp-load-plugins": "^1.1.0",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-util": "^3.0.7",
    "rimraf": "*"
  },
  "scripts": {
    "start": "gulp",
    "build": "gulp sass",
    "postinstall": "node_modules/.bin/rimraf node_modules/**/*.info"
  },
  "private": true
}

```

gulpfile.js
```
var gulp = require('gulp');
var gutil = require('gulp-util');
var $    = require('gulp-load-plugins')();

var sassPaths = [
  'bower_components/foundation-sites/scss',
  'bower_components/motion-ui/src'
];

var theme_path = 'path/to/theme/';

gulp.task('sass', function() {
  return gulp.src(theme_path + 'scss/gh_zurb.scss')
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      includePaths: sassPaths,
      //outputStyle: 'compressed',
      outputStyle: 'expanded',
      sourcemaps: true})
      .on('error', $.sass.logError))
    .pipe($.autoprefixer({
      browsers: ['last 2 versions', 'ie >= 9']
    }))
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest(theme_path +'css'))
    .pipe($.livereload());
});


gulp.task('default', ['sass'], function() {
  gulp.watch([theme_path + 'scss/**/*.scss'], ['sass']);

});

```

**Comment by jackfranklin** [comment]
Oh dear! I'm sorry to hear this.

If you run with `{ DEBUG: true }` as the options do you see anything?

**Comment by jackfranklin** [comment]
Also if you're able to get this in a repo on GitHub that I can clone that would be great.

**Comment by rvdkooy** [comment]
We have the same issue with eslint

We found out that this is related to the fact gulp-load-plugin is now requiring gulplog:
https://github.com/jackfranklin/gulp-load-plugins/blob/master/index.js#L6

gulplog is registering itself with sparkles. 
this will affect the behavior of gulp-util which is also using sparkles to find out which logger to use:
https://github.com/gulpjs/gulp-util/blob/master/lib/log.js#L4

previously it used fancy-log in our case, now it is using gulplog, but we didn't register any handlers for it, so no output!

We are still looking into it, stay tuned!

Ronald
cc @mauricedb

**Comment by codedbypaul** [comment]
I'm having the same issue. Debug doesn't output anything.

My tasks using plugins.plugin() do still work, you just don't see any gulp output.

**Comment by doowb** [comment]
I have a fix for this and added some tests.

Github seems to be caching my previous fork and I'm not able to push up yet. As soon as that's resolved, I'll submit a PR.

**Comment by jackfranklin** [comment]
@doowb awesome, thanks. I'm seeing issues with GitHub too so no rush; if you make the PR I'll merge and release. Really appreciate your work on this.

**Comment by jeffro94** [comment]
I just spent hours trying to fix my project before finding this update was the issue.

**Comment by jsheffers** [comment]
Happening here too.  Downgrading works fine.  Subscribed.

**Comment by doowb** [comment]
@jackfranklin I submitted a PR with changes to be close to what `gulp-utils` uses (based on the code that @rvdkooy linked to). There's also a test to verify the debug logging is running..

**Comment by jackfranklin** [comment]
@doowb thanks for all your work. 1.2.4 is now on npm with the fix applied.

**Comment by rvdkooy** [comment]
awesome :+1:
