### ISSUE TITLE
Change the default pattern to * (match all)

### ISSUE THREAD

**Issue by fracz** [jackfranklin/gulp-load-plugins#122]
I wonder why the default pattern is `['gulp-*', 'gulp.*']`? Why isn't it simply `['*']`?

Such configuration prevents this helper to be used with non-gulp-prefixed dependencies (like `del`, `yargs`, `chalk` etc).

Wouldn't it be great if we could `$.del`, `$.yargs`, `$.chalk` with no extra configuration? Is there any drawback?

One I can think about is a name clash between plugins, but `gulp.something` and `gulp-something` suffers from the same.

**Comment by callumacrae** [comment]
You might be interested in this issue: https://github.com/jackfranklin/gulp-load-plugins/issues/77

**Comment by jackfranklin** [comment]
You could simply pass in [`*`] as the pattern and that would have the desired effect. This plugin was only ever designed for gulp plugins, which is why the pattern is as such.

One could even publish a module `load-plugins` that simply exports `gulp-load-plugins` with the right configuration.
