### ISSUE TITLE
Error if given unknown config keys

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/gulp-load-plugins#123]
See: https://github.com/jackfranklin/gulp-load-plugins/issues/120#issuecomment-248296984 

This will stop annoying issues because of typos :)

**Comment by jameelmoses** [comment]
Although I agree that some fancy logging would be nice for unknown options, the documentation is very clear in detailing the supported options and their respective keys and expected values. I'm hesitant to add more code, or worse more dependencies, to account for typos.
