### ISSUE TITLE
Multiple config locations support

### ISSUE THREAD

**Issue by zslabs** [jackfranklin/gulp-load-plugins#124]
Hi,
Thanks for making this! Looking through the options, I saw that you can specify a location to read the `package.json` from, which definitely saves some time keeping versions up to date across multiple shared packages.

What I was wondering was if it's possible to specify multiple locations to read from:

```
const $ = gulpLoadPlugins({
  config: [require('dep/package.json'), 'package.json']
});
```

I'd imagine if it were to come into conflict with similarly named gulp plugins, that the first occurrence would take precedence and skip over any others. If anyone knows if this is possible I'd appreciate it, otherwise maybe a good feature request? Thanks!

**Comment by jackfranklin** [comment]
A config can be a string  or an object, so in this case I think you could do this yourself with Object.assign, Lodash or similar:

```
config: Object.assign(require('dep/package.json'), require('other-package.json')),
```

Would that work? I haven't tried it myself  but give that a go. If that, or something similar, does work, it would be a good  README  addition if you fancied doing a PR :)

**Comment by zslabs** [comment]
Hey @jackfranklin,
Thanks for the suggestion! Yep, I was able to find a way to make this work. I've created https://github.com/jackfranklin/gulp-load-plugins/pull/125 that adds that to the documentation with a more robust "merge" function. Let me know what you think, thanks!
