### ISSUE TITLE
gulp-sourcemaps has not been detected

### ISSUE THREAD

**Issue by ghost** [jackfranklin/gulp-load-plugins#131]
Thank you for the amazing tool.

Unfortunately,  I faced with strange problem: the `gulp-sourcemaps` has not been detected by `$.sourcemaps`. However, if to use `gulp-sourcemaps`  by regular way, it is visible:

```
const $ = require('gulp-load-plugins')();
const gulp = require('gulp');
const sourcemaps = require('gulp-sourcemaps');

module.exports = options => { 
    
    console.log($.if);
    console.log($.sourcemaps);
    console.log(sourcemaps);

   // ...

```

Console:

```
[Function]
undefined
{ init: [Function: init], write: [Function: write] }
```

**Comment by jameelmoses** [comment]
Were you able to resolve this? I am unable to replicate the issue.

When I console.log() the function as you've done above, I get the following in my console as expected:

```
{ init: [Function: init],
  write: [Function: write],
  mapSources: [Function: mapSources],
  identityMap: [Function: identityMap] }
```

If this is still an issue, let me know, and I'll re-open it. It might help if you can create a repo replicating the issue and send a link here in the issue.
