### ISSUE TITLE
IDE autocomplete

### ISSUE THREAD

**Issue by puggan** [jackfranklin/gulp-load-plugins#136]
I like how this plugin forces me to save the packages, but the
"This frees you up from having to manually require each gulp plugin." don't work well with the IDE:s autocomplete functionality, so ended up with this code:

```js
const plug = require('gulp-load-plugins')({rename: {...}});
// noinspection ConstantIfStatementJS just here for IDE inspection help
if(false) {
    // noinspection UnreachableCodeJS just here for IDE inspection help
    plug.rename = require("gulp-rename");
    ...
```

Is there a better way to get the IDE to know whats available?
(in my case PHPStorm)

**Comment by jameelmoses** [comment]
IDE autocompletion for this plugin is outside of the scope of the plugin. This is meant to easily import gulp plugins by name only without require/import statements for each. I'm sorry I don't have a better answer for you here, but every IDE/text editor handles autocompletion differently, many relying on third-party packages for support.
