### ISSUE TITLE
Is this plugin still managed?

### ISSUE THREAD

**Issue by rowild** [jackfranklin/gulp-load-plugins#137]
The last update was 2 years ago. Meanwhile, some dependencies need update ("npm audit" complains).

Please inform us, if this plugin is deprecated or if there is an update coming soon!

Thanks!

**Comment by callumacrae** [comment]
send a pull request updating the dependencies and poke jack on twitter and i'm sure he'll be happy to merge it :)

**Comment by jameelmoses** [comment]
All vulnerabilities were resolved with #138. I will work to replace deprecated packages in the next release
