### ISSUE TITLE
Maintainers wanted!

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/gulp-load-plugins#139]
Hi all,

I'm not in a position to maintain this plugin as well as it needs. If someone would like to take over, I will happily give you contributor access + npm publish rights.

Please let me know via this issue or DM me on Twitter - @Jack_Franklin.

Thanks!

**Comment by pioug** [comment]
Hello @jackfranklin, I am using `gulp-load-plugins` in my projects at work. So I would happy to help you with the small chores (bump, triage issues, release...). I am doing my best to maintain a couple of other gulp plugins https://www.npmjs.com/~pioug.

Thanks a lot for creating this plugin! The API is great 🌟 Never had a single issue with it.

**Comment by jameelmoses** [comment]
@jackfranklin I'd be interested in taking this on. I heavily use the plugin at work as well, and I'd love to ensure it stays up-to-date and actively maintained.

**Comment by jackfranklin** [comment]
@pioug @jameelmoses I've just added you both as collaborators on the repo 👌

Please feel free to push/merge/close issues/etc, and do whatever you think is best. For now I'll be able to do the releases when you'd like (if you need me, ping me on Twitter (Jack_Franklin) or just email jack@jackfranklin.net). If this goes well I'll then add you to npm and you can be fully in control.

Thank you so much for offering to help out!

**Comment by jameelmoses** [comment]
Sounds good, @jackfranklin!
