### ISSUE TITLE
Extra Parameters for conditional assignment

### ISSUE THREAD

**Issue by simongcc** [jackfranklin/gulp-load-plugins#144]
Hello! I am using gulp-sass for a few years. Recently, it requires to use with  an extra parameter to assign a compiler to it, is it possible when using gulp-load-plugins, pass that parameter to it conditionally so that only gulp-sass will take that?

eg. it require to run like:
const sassFunc = require('gulp-sass')(require('node-sass'));
Since const $ = require('gulp-load-plugins')(); which make the later reassignment impossible. So, assigning the function in one shot is required. i.e. Cannot run
$.sass = sassFunc later on

Thanks in advance.

**Comment by jameelmoses** [comment]
That's correct. You will need to handle `gulp-sass` outside of `gulp-load-plugins` as a manual, individual assignment still without `$.sass`

```
const sass = require('gulp-sass')(require('sass'));
const $ = require('gulp-load-plugins')();
```
