### ISSUE TITLE
Add a mechanism to explicitly include plugins that don't match the pattern?

### ISSUE THREAD

**Issue by alvint** [jackfranklin/gulp-load-plugins#50]
The current API is fine for the vast majority of cases. However, there are a few plugins that don't match the naming convention but are commonly used with Gulp (like `del`). How about adding a way for the user to explicitly include them? I don't like having to access some plugins one way and other plugins another way.

One possibility is to gently and compatibly tweak the contract of `rename` so that plugins mentioned there are loaded regardless of whether the prefix matches. Then this would work and the del plugin would be accessible with `plugins.del`:

```js
gulpLoadPlugins({
  rename: {
    'del': 'del'
  }
});
```

**Comment by alvint** [comment]
Ah! I didn't know you could do that. The "Options" section only showed `pattern` taking a single string pattern, but I guess I should have assumed you could pass in an array of patterns as well. You might want to make that clearer for n00bs like me. That does exactly what I needed in a better way. Thanks!

**Comment by jackfranklin** [comment]
@alvint good point, I will update the documentation :)
