### ISSUE TITLE
Running into issue with gulp-rename.

### ISSUE THREAD

**Issue by crswll** [jackfranklin/gulp-load-plugins#51]
I can do this just fine
````js
var rename = require('gulp-rename');
gulp.src('foo.css').pipe(rename({ suffix: '.min' })).pipe('./dest');
````
but
````js
var $ = require('gulp-load-plugins')();
gulp.src('foo.css').pipe($.rename({ suffix: '.min' })).pipe('./dest');
````
fails with the error
````
[gulp] 'styles' errored after 448 ms Object #<Object> has no method 'rename'
````
Possibly an issue with the `rename` functionality recently added?
https://github.com/jackfranklin/gulp-load-plugins#renaming

**Comment by jackfranklin** [comment]
It could well be something related to that, interesting. I will have a look at this asap.

**Comment by crswll** [comment]
It's working well with every other gulp-* module I have. I also tried `{ lazy: false }`. I should have mentioned that in the opening note.

**Comment by jackfranklin** [comment]
Could you try running a version before the rename functionality was added and see if that works?

**Comment by crswll** [comment]
That didn't work, so I did a bit more research and realized it was my fault. I didn't have gulp-rename in my `package.json` for whatever reason. Sorry to bother you and thanks!
