### ISSUE TITLE
gulp-load-plugins as a dependency of a dependency not loading plugins

### ISSUE THREAD

**Issue by callumacrae** [jackfranklin/gulp-load-plugins#56]
EDIT: Remove all comments until this one: https://github.com/jackfranklin/gulp-load-plugins/issues/56#issuecomment-71681420

I *think* this is the same as #35.

I have the following project which I use to quickly load up gulp tasks in projects where I work without duplicating code: https://github.com/Lostmyname/lmn-gulp-tasks

Pretty much the same file structure described in [this comment](https://github.com/jackfranklin/gulp-load-plugins/issues/35#issuecomment-49170938), and it's looking in the top package.json, not the bottom one:

```
~/Sites/lmn/monkey master*  6m 44s  ⇡
❯ npm install lmn-gulp-tasks
npm WARN package.json lmn-monkey@3.0.1 No repository field.
npm WARN package.json browsernizr@1.0.2 No repository field.
lmn-gulp-tasks@1.0.0 node_modules/lmn-gulp-tasks
├── jshint-stylish@1.0.0 (log-symbols@1.0.1, text-table@0.2.0, string-length@1.0.0, chalk@0.5.1)
├── gulp-plumber@0.6.6 (through2@0.6.3)
├── gulp-jshint@1.9.0 (rcloader@0.1.2, minimatch@1.0.0, lodash@2.4.1, through2@0.6.3)
├── gulp-util@3.0.2 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@2.4.1, replace-ext@0.0.1, minimist@1.1.0, chalk@0.5.1, multipipe@0.1.2, vinyl@0.4.6, through2@0.6.3, lodash.template@2.4.1, dateformat@1.0.11)
├── gulp-minify-css@0.4.3 (memory-cache@0.0.5, bufferstreams@0.0.2, through2@0.6.3, vinyl-sourcemaps-apply@0.1.4, clean-css@3.0.7)
├── stylus@0.49.3 (css-parse@1.7.0, mkdirp@0.3.5, debug@2.1.1, glob@3.2.11, sax@0.5.8, source-map@0.1.43)
├── gulp-compass@2.0.3 (which@1.0.8, through2@0.6.3)
├── jshint@2.6.0 (strip-json-comments@1.0.2, underscore@1.6.0, console-browserify@1.1.0, exit@0.1.2, minimatch@1.0.0, shelljs@0.3.0, cli@0.6.5, htmlparser2@3.8.2)
├── gulp-jscs@1.4.0 (object-assign@2.0.0, through2@0.6.3, jscs@1.10.0)
├── gulp-autoprefixer@2.1.0 (object-assign@2.0.0, through2@0.6.3, vinyl-sourcemaps-apply@0.1.4, autoprefixer-core@5.0.0)
└── browserify@8.1.1 (https-browserify@0.0.0, tty-browserify@0.0.0, builtins@0.0.7, constants-browserify@0.0.1, process@0.10.0, path-browserify@0.0.0, os-browserify@0.1.2, isarray@0.0.1, inherits@2.0.1, commondir@0.0.1, string_decoder@0.10.31, stream-browserify@1.0.0, defined@0.0.0, domain-browser@1.1.3, shell-quote@0.0.1, xtend@3.0.0, shallow-copy@0.0.1, deep-equal@0.2.1, querystring-es3@0.2.1, assert@1.3.0, timers-browserify@1.2.0, punycode@1.2.4, util@0.10.3, vm-browserify@0.0.4, events@1.0.2, parents@1.0.1, console-browserify@1.1.0, subarg@1.0.0, url@0.10.2, readable-stream@1.0.33, http-browserify@1.7.0, deps-sort@1.3.5, through2@1.1.1, resolve@0.7.4, shasum@1.0.1, buffer@3.0.1, concat-stream@1.4.7, glob@4.3.5, duplexer2@0.0.2, browser-resolve@1.6.0, JSONStream@0.8.4, labeled-stream-splicer@1.0.2, browser-pack@3.2.0, crypto-browserify@3.9.10, umd@2.1.0, insert-module-globals@6.2.0, syntax-error@1.1.2, browserify-zlib@0.1.4, module-deps@3.6.4)

~/Sites/lmn/monkey master*  15s  ⇡
❯ gulp
[16:00:49] Using gulpfile ~/Sites/lmn/monkey/gulpfile.js
[16:00:49] Starting 'html'...
[16:00:49] Starting 'js-quality'...
[16:00:49] 'js-quality' errored after 8.71 ms
[16:00:49] Error: Cannot find module 'gulp-plumber'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.defineProperty.get (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp-load-plugins/index.js:56:18)
    at Gulp.jsQualityTask (/Users/callumacrae/Sites/lmn/monkey/node_modules/lmn-gulp-tasks/tasks/js-quality.js:15:33)
    at module.exports (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
[16:00:49] Finished 'html' after 62 ms
```

If I replace `plugins.plumber(` with just `plumber(` and require it manually, it errors about the next module instead.

Interestingly, it doesn't happen if I npm link the `lmn-gulp-tasks` project in—it only happens when I actually install it through npm.

Any ideas what's happening?

**Comment by callumacrae** [comment]
README says this:

```
// where to find the plugins, by default  searched up from process.cwd() 
```

Wouldn't `__dirname` be better?

```
process.cwd(): /Users/callumacrae/Sites/lmn/monkey
__dirname: /Users/callumacrae/Sites/lmn/monkey/node_modules/lmn-gulp-talks
```

**Comment by callumacrae** [comment]
I apologise for vomiting text all over this issue! I was thinking through my keyboard, again.

It looks like it isn't an issue with gulp-load-plugins: because I'm loading gulp-load-plugins both in my project, and in lmn-gulp-tasks, it's only taking the first one, which isn't working. It looks like it's just a problem with node.

This is probably even more specific than the issue I initially linked to! I guess this is more a node question, but is there any way around this behaviour?

**Comment by callumacrae** [comment]
I've figured out the *actual* problem:

```
myproject
 - gulpfile.js
 - package.json (1)
 - node_modules (1)
   - gulp-load-plugins
   - lmn-gulp-tasks
     - index.js
     - package.json (2)
     - node_modules (2)
```

package.json (2) has gulp-load-plugins as a dependency, but because so does package.json (1), so it is loaded into node_modules (1).

When I call `require('gulp-load-plugins')()` from `lmn-gulp-tasks/index.js` it runs the gulp-load-plugins from node_modules (1), so even though it's got the correct package.json, it's got the wrong node_modules directory and so cannot load the plugins.

Short of replicating part of the `require` function and setting `options.requireFn`, is there any way around this?

**Comment by callumacrae** [comment]
You should be able to replicate this on this branch of Lostmyname/monkey: https://github.com/Lostmyname/monkey/tree/lmn-gulp-tasks

**Comment by jackfranklin** [comment]
Hey! Sorry for my slow reply, I have been away. Good stuff debugging this, this is really useful. Determined to try to track down the source of this bug and how we can fix it.

If I'm right, the below is the expected behaviour, right?

```
myproject
 - gulpfile.js ===> gulp-load-plugins needs to use node_modules (1)
 - package.json (1)
 - node_modules (1)
   - gulp-load-plugins
   - lmn-gulp-tasks
     - index.js ===> gulp-load-plugins needs to use node_modules (2)
     - package.json (2)
     - node_modules (2)
```

I can't imagine we have to override `require` or reimplement some of it - I'm sure we can do this just by refining the code we have. I'll try to dig into this if I get time soon.

**Comment by callumacrae** [comment]
Yeah, that's the expected behaviour, and it's attempting to use node_modules (1).

I spent quite a bit of time trying to work out a fix, and the best I came up with was basically reimplementing a lot of `require`: finding the module starting from the specified package.json, reading the `main` path, and including that. Haven't written it yet, but would be willing to—this is making things tricky at work!

**Comment by iarna** [comment]
So npm@3 is going to exacerbate this issue even further by further flattening install trees. Could `gulp-load-plugins` look the package.json (maybe in addition to reading node_modules)? If you use `read-package-json` you'll get exactly the same semantics `npm` has when reading them, including supporting some subtle corner cases and normalizing the fields.

**Comment by callumacrae** [comment]
I opened a pull request fixing this specific issue here, but it isn't perfect either: #57

I'm not sure how reading the package.json would help in this case: wouldn't it be best to read the node_modules file as in the PR I opened, and then use `findup` to look to see if the module is further up the tree?

**Comment by dulcedilip** [comment]
i having similar sought of problem 
i am all gulp tasks as one project called "tasks" where it is having it's own package.json.
 when i am trying to use var $ = require(gulp-load-plugins)(); in tasks project which in turn finding package.json in tasks folder rather it need to find node_modules/gulp-load-plugins/ package.json.

when i renamed tasks/package.json to tasks/package1.json . everything is working fine.
 any suggestions on this ? appreciated your help
Note: tasks is in node_modules folder.

**Comment by jackfranklin** [comment]
@dulcedilip I think here you could override the `config` option and set the right path to the package.json you'd like it to use?

**Comment by dulcedilip** [comment]
i resolved this problem in moving  grunt-load-plugins to package.json into tasks project, which solved my problem. yeah i can use by override the config option i dont want to change core cwd.path.

Thanks for the support.
