### ISSUE TITLE
Can't get this to work for non-gulp plugins

### ISSUE THREAD

**Issue by Jakobud** [jackfranklin/gulp-load-plugins#60]
I have this `package.json`:

```
{
  "dependencies": {
    "gulp": "*",
    "gulp-load-plugins": "~0.8.0",
    "del": "*"
  }
}
```

I have this gulp file:

```
var gulp = require('gulp');
var plugins = require('gulp-load-plugins')();

gulp.task('build', function(){

	plugins.del.sync('./build');
});
```

I get this:

```
 TypeError: Cannot call method 'sync' of undefined
```

So it isn't able to load the `del` plugin. I figured it was because it didn't start with `gulp-` so I tried this:

```
var gulp = require('gulp');
var plugins = require('gulp-load-plugins')({
  rename: {
    'del': 'del'
  }
});
```

But that didn't make a difference. Am I doing something wrong? How do you use this with non-gulp-specific plugins?

**Comment by matijakovacevic** [comment]
It's not an issue...you are doing it wrong.

If you want non gulp plugins to load also, you have to change the pattern (to include non gulp files).

```
plugins = require('gulp-load-plugins')({
        pattern: '*',
});
```

and then access it with 
```

**Comment by Jakobud** [comment]
Ah I totally missed that option. Thank you! Great plugin. Speeds up scripts a ton.
