### ISSUE TITLE
non-gulp-specific- plugins vol.2 - pattern options 

### ISSUE THREAD

**Issue by miccferr** [jackfranklin/gulp-load-plugins#62]
Similar to issue #60 I'm trying to import and rename non-gulp-specific plugins via the pattern option.
@matijakovacevic suggested the use of [pattern = *] which seems correct.

Though if i try it, I get this error pointing at another package that I have in my packages.json:
```"TypeError: Cannot redefine property: modernizr"```
And if i use the deafult options ``` ['gulp-*', 'gulp.*'] ``` I'm still not importing correctly the plugins..

Am I messing too much with the glob function?
Is this just modernizr related?
What would then be the best way to import&rename the plugins (both gulp- and non gulp-..)?

Thanks!

**Comment by jackfranklin** [comment]
Do you have modernizr twice in your package.json by any chance?

I've said before that I don't encourage using this package to load in every module you've ever got, so I'm not too willing to support it. Redefine the pattern and the options and it should work though.

**Comment by jackfranklin** [comment]
Going to close this now. Feel free to reopen.
