### ISSUE TITLE
Shrinkwrap

### ISSUE THREAD

**Issue by entozoon** [jackfranklin/gulp-load-plugins#67]
Is there a way to make this work after using npm shrinkwrap?
A package.json file would look more like:
```
{
  "name": "Builder",
  "dependencies": {
    "npm-shrinkwrap": "*"
  },
}
```
Then lazy load would need to somehow use the npm-shrinkwrap.json file instead..

**Comment by jackfranklin** [comment]
Interesting, I see no reason why we couldn't make it work with a shrinkwrapped file. I don't have time at the moment but if someone does and wants to PR I'm well up for that :+1:

**Comment by entozoon** [comment]
Was this closed because it was done?

**Comment by jackfranklin** [comment]
Woops, sorry, closed the wrong one. It's not done but I have no time to work on it. I'll love a PR though :)

**Comment by entozoon** [comment]
Was this ever looked at in the end? I'd have a go but it's beyond my abilities unfortunately..
I keep shrink wrapping sites to future-proof them, and then not being able to understand why they don't work - forgetting it's because of this issue :(

**Comment by callumacrae** [comment]
When I've used shrinkwrap before, we've used both package.json and npm-shrinkwrap.json, it generally works a lot better.

Pretty sure setting the `config` options to `npm-shrinkwrap.json` will still work. It's still stored as `root.dependencies`.

**Comment by jackfranklin** [comment]
@entozoon did you try what @callumacrae suggested?

I think that should work so I'm going to close this, but please feel free to comment if it doesn't and I'll reopen.

**Comment by entozoon** [comment]
I've given that a go, and having a weird problem.. 
```
var plugins = require("gulp-load-plugins")({
	pattern: ['gulp-*', 'gulp.*', 'main-bower-files'],
	replaceString: /\bgulp[\-.]/,
	config: 'npm-shrinkwrap.json'
});
```
Gives this error:
```
Error: Cannot find module 'npm-shrinkwrap.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    ...
```

Which I can't fathom because my ``npm-shrinkwrap.json`` file is definitely there, in process.cwd().
And I know it should work because if I rename ``npm-shrinkwrap.json`` to ``package.json`` (getting rid of my current one) and remove the ``config`` option .. it works!

As a workaround I guess I could just use the shrinkwrap as package.json in general? Seems like a reasonable thing to do anyway thinking about it

**Comment by jackfranklin** [comment]
Could you try:

```
config: path.join(__dirname,'npm-shrinkwrap.json')
```

And see if that works?

**Comment by entozoon** [comment]
Aaah, success!
That coupled with the necessary:
```
var path = require("path");
```
I must admit I'm tempted to carry on using the npm shrinkwrap stuff in the package.json file.. seems quite a neat and tidy way of doing things.

Thank you for the help and solution both of you :)

**Comment by jackfranklin** [comment]
It's annoying that we have to do that though for it to work - might be something to look into. @callumacrae have you come across this before? I vaguely remember you debugging this but I could well be wrong.

@entozoon glad it's working!

**Comment by callumacrae** [comment]
Nah, I've never used npm-shrinkwrap.json without also having a package.json, so haven't ran in to anything like this.

**Comment by jackfranklin** [comment]
I didn't mean shrinkwrap specifically, more just the weirdness of having to specify the `path.join(__dirname,...)` nuisance.
