### ISSUE TITLE
Pass plugin options into gulp-load-plugins

### ISSUE THREAD

**Issue by TheDutchCoder** [jackfranklin/gulp-load-plugins#78]
I'm having trouble passing in custom objects for certain gulp plugins.

Take the following example:
```js
var s3 = require('gulp-s3-upload')({
        accessKeyId:        "YOUR DEV ID",
        secretAccessKey:    "YOUR SECRET"
});
```

If i use gulp-load-plugins and pass it the same object, the plugin will not configure itself. This makes sense, because how would gulp-load-plugins know which plugin to pass the object to.

Example:
```js
var plugins = require('gulp-load-plugins')({
        accessKeyId:        "YOUR DEV ID",
        secretAccessKey:    "YOUR SECRET"
});

So my question is: is there a way of configuring plugins at the parsing stage?

Maybe I'm just missing something obvious, but it would be great if this could be done.

**Comment by callumacrae** [comment]
```js
var plugins = require('gulp-load-plugins')();

var s3 = plugins.s3Upload({
        accessKeyId:        "YOUR DEV ID",
        secretAccessKey:    "YOUR SECRET"
});
```

Does that work?

**Comment by TheDutchCoder** [comment]
Yes that does work, but that defeats a bit of the purpose of using plugins.s3Upload.
For some reason it doesn't work in the pipe.

Is that a bug in the plugin than?

E.g. this doesn't work:
```js
return gulp.src([
        'dist/**'
        ])
        .pipe(plugins.plumber(plumber.options))
        .pipe(plugins.s3Upload({
            accessKeyId: 'foo',
            secretAccessKey: 'bar'
        }))
        .pipe(plugins.s3Upload({
            Bucket: 'soshal-resources/soshal-theme',
            ACL:    'public-read'
        }));
```

**Comment by jackfranklin** [comment]
@TheDutchCoder did you get anywhere with this? Being able to pass arguments into plugins is something I'm not sure I'd like to add - I'd rather it be done explicitly as @callumacrae showed.

If you're still stuck on the above though please feel free to reopen, and apologies for my slow reply.

**Comment by TheDutchCoder** [comment]
Yeah that worked, but as I said, it sort of defeats the purpose of having one place to load all plugins and then to have to manually configure some plugins afterwards, instead of being able to pass a config object when needed in the pipe.

It's not a big deal, but was just wondering if this plugin would support something like that.

Not sure how gulp works on the inside, but it seems counter intuitive that I can't pass a config object during a pipe.

Then again, because it's a one off setup, it doesn't really fit in a pipe either, so that's why passing it when gulp-load-plugins runs would be great ;)

No need to re-open.
