### ISSUE TITLE
gulp-load-plugins only loads one plugin

### ISSUE THREAD

**Issue by pushkin-** [jackfranklin/gulp-load-plugins#80]
I initially posted this as a comment to #70 but considering that the proposed solution didn't work and more importantly the problem I'm having is not identical, I'm opening a new issue.

This plugin is only loading one of the many plugins I have.

Here's my simplified `gulpfile.js`:

    var gulp = require('gulp');
    var plugins = require('gulp-load-plugins')({
        lazy: false
    });

In one of my default tasks, I'm logging `JSON.stringify(plugins)`, which gives me:

    {
      "util": {
          "colors": {
              "enabled": true,
              "styles": {
                  "reset": {
                      "open": "\u001b[0m",
                      "close": "\u001b[0m",
                      "closeRe": {}
                  },
    ...
`util` is the only thing there. 

`util` seems to refer to `gulp-util`. The plugin seems to default to removing the gulp prefix even if I'm not using the parameter replaceString (is this a bug?). If I add the parameter with an incorrect value like so `replaceString: '/^gulp(-|\.)/'` `util` becomes `gulpUtil`. I find this a little strange since the plugin is named 'gulp-util' and I'm not camelizing it.

I examined an `strace` of the call, but can't catch the culprit. Here's a brief version of the salient bits.
The first plugin, `gulp-uglify`, does not load. The second, `gulp-util`, does.

    stat("/a/path/app/node_modules/gulp-uglify", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
    stat("/a/path/app/node_modules/gulp-uglify.js", 0x7ffc64e32c90) = -1 ENOENT (No such file or directory)
    stat("/a/path/app/node_modules/gulp-uglify/package.json", {st_mode=S_IFREG|0664, st_size=2114, ...}) = 0
    open("/a/path/app/node_modules/gulp-uglify/package.json", O_RDONLY) = 9
    ioctl(9, FIOCLEX)                       = 0
    fstat(9, {st_mode=S_IFREG|0664, st_size=2114, ...}) = 0
    read(9, "{\n  \"name\": \"gulp-uglify\",\n  \"de"..., 2114) = 2114
    close(9)                                = 0
    stat("/a/path/app/node_modules/gulp-uglify/index.js", {st_mode=S_IFREG|0664, st_size=158, ...}) = 0
    stat("/a/path/app/node_modules/gulp-uglify/index.js", {st_mode=S_IFREG|0664, st_size=158, ...}) = 0
    stat("/a/path/app/node_modules/gulp-util", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
    stat("/a/path/app/node_modules/gulp-util.js", 0x7ffc64e32c90) = -1 ENOENT (No such file or directory)
    stat("/a/path/app/node_modules/gulp-util/package.json", {st_mode=S_IFREG|0664, st_size=2297, ...}) = 0
    open("/a/path/app/node_modules/gulp-util/package.json", O_RDONLY) = 9
    ioctl(9, FIOCLEX)                       = 0
    fstat(9, {st_mode=S_IFREG|0664, st_size=2297, ...}) = 0
    read(9, "{\n  \"name\": \"gulp-util\",\n  \"desc"..., 2297) = 2297
    close(9)                                = 0
    stat("/a/path/app/node_modules/gulp-util/index", 0x7ffc64e32c30) = -1 ENOENT (No such file or directory)
    stat("/a/path/app/node_modules/gulp-util/index.js", {st_mode=S_IFREG|0664, st_size=553, ...}) = 0
    stat("/a/path/app/node_modules/gulp-util/index.js", {st_mode=S_IFREG|0664, st_size=553, ...}) = 0
    write(1, "{\n    \"util\": {\n        \"colors\""..., 4537{

So it does read from the appropriate plugins (`read(9, "{\n  \"name\": \"gulp-uglify\",\n  \"de"..., 2114)`), but only writes `util`.

Part of my `package.json`:

    ...
    "devDependencies": {
        "gulp": "^3.9.0",
        "gulp-load-plugins": "^1.0.0-rc.1",
        "gulp-uglify": "^1.2.0",
        "gulp-util": "^3.0.6"
    }
    ...

My guess is that this issue has something to do my environment.

If there is a need for it, I can attach the entire output of the `strace` call.

**Comment by callumacrae** [comment]
Would you be to set up a repo that we can replicate this in?

**Comment by pushkin-** [comment]
[Here](https://github.com/pushkin-/gulp-load-plugin-issue) is the repo.

**Comment by callumacrae** [comment]
Replicated

**Comment by pushkin-** [comment]
So you replicated the problem? That's strange.
Considering that such a simple example was failing, I was expecting the issue to be associated with my environment.

Is `gulp-util` required for the plugin to work? I tried uninstalling it to see if I would get an empty object,  but it says `Cannot find module 'gulp-util'`. It's not in my `package.json` nor am I referencing it anywhere in my gulpfile.

**Comment by jackfranklin** [comment]
@callumacrae did you get anywhere with this? Let me know if I can be of use.

**Comment by pushkin-** [comment]
Replicated on Windows 8.1. Same issue.

**Comment by callumacrae** [comment]
Sorry, should have been clearer: not really capable of typing right now except with one hand (broke my collarbone), so won't be able to fix this right now.

**Comment by jackfranklin** [comment]
@callumacrae ouch! No worries; @pushkin- I'll try to take a look if I get some spare time.

**Comment by pushkin-** [comment]
@jackfranklin [Here's](https://github.com/pushkin-/gulp-load-plugin-issue) the repo.

**Comment by jackfranklin** [comment]
@pushkin- sorry I haven't got round to this issue, I'll try to take a look.

In the mean time, if you upgrade to gulp-load-plugins v1.1 and set `DEBUG: true`, does any of the output help us debug at all?

**Comment by john-benson** [comment]
@jackfranklin 

Not sure if this is still needed; but since no one has responded in a couple of months and the issue is still open:

Run on Windows 10, 64 bit
gulp: 3.90
npm: 3.3.6
node: 4.1.2

Executing:
```
var plugins = require('gulp-load-plugins')({
  lazy:false, DEBUG: true
});
```

Results in:
```
[00:10:37] gulp-load-plugins: Debug enabled with options: {"lazy":false,"DEBUG":true}
[00:10:37] gulp-load-plugins: 13 plugin(s) found: angular2 es6-promise es6-shim reflect-metadata rxjs systemjs zone.js browser-sync gulp gulp-debug gulp-load-plugins gulp-typescript wrench
[00:10:37] gulp-load-plugins: renaming gulp-debug to debug
[00:10:37] gulp-load-plugins: requiring gulp-debug...
[00:10:37] gulp-load-plugins: renaming gulp-typescript to typescript
[00:10:37] gulp-load-plugins: requiring gulp-typescript...
```

The debug statements stops, and my simple log
```
console.log(JSON.stringify(plugins));
```

Outputs:
```
{}
```

**Comment by john-benson** [comment]
I had originally thought I reproduced this; but it appears I could not.

If anyone else is having this problem, make sure you correctly spell the name of the resulting plugins.

**Comment by jackfranklin** [comment]
@pushkin- I just downloaded your test repo, then made sure I was running the latest version:

```
npm install gulp-load-plugins@1.1.0 --save
```

I then turned `DEBUG: true` on and also updated the console log so it just logged the keys:

```js
'use strict';

var gulp = require('gulp');
var path = require('path');

var $ = require('gulp-load-plugins')({
    //scope: ['devDependencies'],
    //config: path.join(__dirname, 'package.json'),
  DEBUG: true,
  lazy: false
});

gulp.task('test', function() {
    console.log(JSON.stringify(Object.keys($), null, 4));
});

gulp.task('default', ['test']);
```

Running `gulp` gives me:

```
[10:27:06] gulp-load-plugins: Debug enabled with options: {"DEBUG":true,"lazy":false}
[10:27:06] gulp-load-plugins: 8 plugin(s) found: gulp-load-plugins jquery path underscore gulp gulp-load-plugins gulp-rename gulp-util
[10:27:06] gulp-load-plugins: renaming gulp-rename to rename
[10:27:06] gulp-load-plugins: requiring gulp-rename...
[10:27:06] gulp-load-plugins: renaming gulp-util to util
[10:27:06] gulp-load-plugins: requiring gulp-util...
[10:27:06] Using gulpfile ~/git/gulp-load-plugin-issue/gulpfile.js
[10:27:06] Starting 'test'...
[
    "rename",
    "util"
]
[10:27:06] Finished 'test' after 362 μs
[10:27:06] Starting 'default'...
[10:27:06] Finished 'default' after 5.78 μs
```

As you can see, it finds the two plugins as I would expect. Could you try running it at your end and see if it now works?

**Comment by jackfranklin** [comment]
> util seems to refer to gulp-util. The plugin seems to default to removing the gulp prefix even if I'm not using the parameter replaceString (is this a bug?). If I add the parameter with an incorrect value like so replaceString: '/^gulp(-|\.)/' util becomes gulpUtil. I find this a little strange since the plugin is named 'gulp-util' and I'm not camelizing it.

If this is still happening for you on the latest version, could you open a new issue so it's easier to track separately to this one? Thanks :)

**Comment by pushkin-** [comment]
@jackfranklin Huh. Using your gulpfile (printing `Object.keys($)` vs the whole object), I get the same output you got. And after successfully using the loaded plugin, I can verify that it does indeed work.

Printing the whole object, the only key I see is `util` for some reason (like in my original post). But printing just the keys gets me both `util` and `rename`.

Not sure what the issue was before.

**Comment by jackfranklin** [comment]
@pushkin- perfect, so it's all working! Weird regarding it printing or not :/ If both the plugins work as normal though that's good. I'm going to close but please comment / start a new issue if anything else goes awry. I haven't tested on Windows so there may well be more bugs.
