### ISSUE TITLE
loading non-gulp modules?

### ISSUE THREAD

**Issue by Manaus** [jackfranklin/gulp-load-plugins#83]
Hi, 
does this module load other modules too? Like browser-sync and the like? Or just those with a `gulp-` prefix? If it does, what name is used for those modules? In case of some longer names, like `gulp-less-watcher`, what is the generated name? 

Thanks

**Comment by callumacrae** [comment]
Check out this issue for info on loading non-gulp stuff: https://github.com/jackfranklin/gulp-load-plugins/issues/77

`gulp-less-watcher` would be loaded as `plugins.lessWatcher`.

**Comment by carloshpds** [comment]
Use the `pattern` property for that ;)

**Comment by Manaus** [comment]
Thanks guys
