### ISSUE TITLE
Can't load vinyl-ftp plugin.

### ISSUE THREAD

**Issue by diazemiliano** [jackfranklin/gulp-load-plugins#84]
I've tried with:
``` coffeescript
plugins = require('gulp-load-plugins')( camelize: false)
plugins.vinylftp ...
```
and 
``` coffeescript
plugins = require('gulp-load-plugins')( camelize: true)
plugins.vinylFtp ...
```
But I haven'y anithing.

**Comment by callumacrae** [comment]
gulp-load-plugins only loads plugins beginning with `gulp-`—it's designed to load gulp plugins, not all modules. Check out the pattern options, or just require it manually.

**Comment by diazemiliano** [comment]
Ok thanks!

**Comment by jackfranklin** [comment]
@callumacrae thanks for such a speedy reply! @diazemiliano glad you got it sorted :)
