### ISSUE TITLE
support task dependency tree listing

### ISSUE THREAD

**Issue by sandipchitale** [jackfranklin/gulp-load-plugins#85]
It will be useful to see task dependency tree.

Excellent plugin BTW.

**Comment by shinnn** [comment]
It's ready implemented in the [gulp CLI](https://github.com/gulpjs/gulp/blob/cbd69632083e21431573409312e7ed00bafc1d83/docs/CLI.md) and  should not be reimplemented in this project.

> `-T` or `--tasks` will display the task dependency tree for the loaded gulpfile

**Comment by sandipchitale** [comment]
Oops...was not aware if it. Thanks.
