### ISSUE TITLE
Load only gulp plugins or is there a easy way to get all packages?

### ISSUE THREAD

**Issue by carloshpds** [jackfranklin/gulp-load-plugins#93]
Is there an easier way to get all node modules declared in package.json?
I tried to use `*` as pattern and worked well for the most of plugins, but get some instability for `gulp-protractor`.

`TypeError: Cannot redefine property: protractor`
Is there some incompatibility?

I've seen a related issue #62, so should i use this module only for a gulp plugins and use something like [load-modules](https://www.npmjs.com/package/load-modules) for other modules?

---
Anyway, this is the flux of the problem:

`My code: `
```
var plugins = require('gulp-load-plugins')({
  pattern: [
    '*',
    '!gulp'
  ]
});
```

`Error:`
```
node_modules/gulp-load-plugins/index.js:66
      Object.defineProperty(finalObject, requireName, {
             ^

TypeError: Cannot redefine property: protractor
    at Function.defineProperty (native)
    at /Users/carloshenrique/Documents/workspace/personal/BaseBuildAngular/node_modules/gulp-load-plugins/index.js:66:14
    at Array.forEach (native)
    at module.exports (/Users/carloshenrique/Documents/workspace/personal/BaseBuildAngular/node_modules/gulp-load-plugins/index.js:55:30)
```

My fix at this moment: 
```
var plugins = require('gulp-load-plugins')({
  pattern: [
    '*',
    '!gulp',
    '!protractor'
  ]
});
```

**Comment by carloshpds** [comment]
So, i found the problem and why my fix works, i have `gulp-protractor` AND `protractor` in my package.json. But the answer is still valid :)

**Comment by jackfranklin** [comment]
Perfect, glad you would a work around. I'm going to close this for now as I don't really see this as an issue with the plugin, other than perhaps we could provide a nicer error message.

**Comment by carloshpds** [comment]
Yeah!  Maybe a better error message would help to figure it out faster .
I'm gonna fork it and make a pull request later :smile:

**Comment by jackfranklin** [comment]
@carloshpds perfect! :)
