### ISSUE TITLE
Swap out JSHint for ESLint

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/gulp-load-plugins#96]
There is a `.jshintrc` file but it's out of date and it doesn't run on Travis, so I've no doubt the code is breaking the jshint rules!

The steps I'd take for this PR would be:

- [ ] Remove `.jshintrc` and get rid of jshint as a dependency from `package.json`
- [ ] Add `eslint` as a developer dependency (`npm install eslint --save-dev`)
- [ ] Follow the [eslint getting started guide](http://eslint.org/docs/user-guide/getting-started) to create an eslint config that we can run against our files.
- [ ] Go through any of the failures that ESLint finds (I'm sure there will be some!) and either:
   - If you think ESLint is correct, fix the code
   - If you think the code is fine, update the ESLint configuration with the corresponding rule
   - You can find a [big list of ESLint rules here](http://eslint.org/docs/user-guide/configuring)
   - If you're not sure if to edit the code or add a rule, leave a comment and ask :)
- [ ] Update `npm test` so it runs `eslint` before running the tests. This will ensure that Travis builds fail if ESLint fails.

And that's about it! Please feel free to reach out to me with any questions.

**Comment by ryan-codingintrigue** [comment]
I'd like to tackle this - what kind of eslint config are you looking for, just recommended rules plus spacing/quotes?

**Comment by jackfranklin** [comment]
@ryan-codingintrigue amazing! Recommend rules + spacing/quotes would be a great place to start. We can always edit that later in future PRs.

**Comment by jackfranklin** [comment]
Closed by #97
