### ISSUE TITLE
How to change the port of livereload ?

### ISSUE THREAD

**Issue by Erichain** [jackfranklin/gulp-load-plugins#98]
If I have multiple apps started at the same time, aren't they conflicted ?

``` javascript
var gulp = require('gulp');
var plugins = require("gulp-load-plugins")();

gulp.task('connect', plugins.connect.server({
    root: ['build'],
    port: 9000,
    livereload: true,
    open: true
}));
```

Now I just know how to set options above. The port of livereload is 35729. So how to change the port of livereload ?

**Comment by callumacrae** [comment]
This isn't an issue with gulp-load-plugins, if anything it is an issue with gulp-connect.

[gulp-connect is blacklisted](https://github.com/gulpjs/plugins/blob/master/src/blackList.json#L23). Just use connect directly.

**Comment by jackfranklin** [comment]
Yup, as @callumacrae this isn't a specific issue to this project, closing.
